### ISSUE TITLE
Readme does not include some dependencies

### ISSUE THREAD

**Issue by Shumakriss** [sciurus/vagrant-mutate#65]
Vagrant-mutate has a dependency on ruby-libvirt which depends on the libvirt headers. yum and apt-get seem to provide libvirt-devel for some major systems: https://github.com/jedi4ever/veewee/issues/510

The reason I call it out is that vagrant plugin install vagrant-mutate does not fail nicely and cannot resolve the depenedency so it might be good to inform users.

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.5.2), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.5.2'` succeeds before bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

From vagrant plugin install output:

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /home/chris/.vagrant.d/gems/gems/ruby-libvirt-0.5.2 for inspection.
Results logged to /home/chris/.vagrant.d/gems/extensions/x86_64-linux/ruby-libvirt-0.5.2/gem_make.out

**Comment by sciurus** [comment]
Gooid point; can you submit a PR updating the README?
