### ISSUE TITLE
Generated box name should be based on name not version

### ISSUE THREAD

**Issue by Shumakriss** [sciurus/vagrant-mutate#66]
I can provide system specs if necessary but when I vagrant mutate it seems to use the original box version as the new box name. It should probably reuse the old name and append something like '-libvirt'

**Comment by sciurus** [comment]
vagrant-mutate should not change the box name. Can you delete the new box, rerun your mutate command with `VAGRANT_LOG=info`, and send me

* the mutate command you are running
* its output
* the output of `find ~/.vagrant.d/boxes/ -type d`
