### ISSUE TITLE
Unconventional name for the "input provider" option

### ISSUE THREAD

**Issue by xicesky** [sciurus/vagrant-mutate#68]
A rather minor issue: Usually options with multiple words are seperated by dashes, not by underscore - if you get it wrong, vagrant mutate also does not give u a very helpful error message:
```
vagrant mutate debian-7.8.0-amd64 libvirt --input-provider=virtualbox
An invalid option was specified. The help for this command
is available below.
```

Of course the command should be --input_provider=virtualbox
A more helpful error message would be "invalid option: --input-provider".

**Comment by sciurus** [comment]
The error message "An invalid option was specified. The help for this command is available below." is generated by [vagrant itself](https://github.com/mitchellh/vagrant/blob/91f416ec5e09f49da859822df444f34ca8f68e11/templates/locales/en.yml#L624), not vagrant-mutate.

I see your point about the underscore. I'm open to changing that if you'd like to submit a PR.

**Comment by xicesky** [comment]
I'm not really into ruby, but i'll see what i can do. Sound like a faily minor change.
