### ISSUE TITLE
Add option to specify the box name for downloaded boxes

### ISSUE THREAD

**Issue by michaelheyvaert** [sciurus/vagrant-mutate#70]
When I tried to import a box from a custom url I got the following result:
```bash
$ vagrant mutate http://<server_url>ms25_2014-10-31.box libvirt
Downloading box 31 from http://<server_url>/ms25_2014-10-31.box
Extracting box file to a temporary directory.
Converting 31 from virtualbox to libvirt.
```
would it be possible to add a --box-name flag to override the derived box name?

**Comment by sciurus** [comment]
Would it be okay if `ms25_2014-10-31` was the box name instead of `31`?

The issue is that vagrant-mutate uses the regular expression `(\w+).box$` to extract the box name but `-` is not considered a word character. I'll change the regex to `([-\w]+).box$`.

**Comment by michaelheyvaert** [comment]
this is perfect, thanks!
