### ISSUE TITLE
"mutate" is unknown vagrant command after plugin install

### ISSUE THREAD

**Issue by muelli** [sciurus/vagrant-mutate#74]
I've installed the plugin (`vagrant plugin install mutate vagrant-libvirt vagrant-proxyconf`) and tried to follow the instructions, which say "The basic usage is vagrant mutate box-name-or-file-or-url output-provider", but it doesn't recognise `mutate` as a valid command.

```
muelli@cloudbox:~$ vagrant plugin list
mutate (1.0.0)
vagrant-libvirt (0.0.30)
vagrant-proxyconf (1.5.1)
muelli@cloudbox:~$ vagrant --version
Vagrant 1.7.4
muelli@cloudbox:~$ vagrant mutate http://files.vagrantup.com/precise64.box libvirt
Usage: vagrant [options] <command> [<args>]

```

**Comment by sciurus** [comment]
You get that error because you didn't install vagrant-mutate, you installed [mutate](https://rubygems.org/gems/mutate/versions/1.0.0). You need to run `vagrant plugin install vagrant-mutate`.
