### ISSUE TITLE
Converted Box gets wrong title

### ISSUE THREAD

**Issue by ofrzeta** [sciurus/vagrant-mutate#75]
Tried to convert a box of the Discourse forum software. This kind of worked but the resulting libvirt box got a wrong "name", that is the number 0:

    $ vagrant mutate http://discourse-vms.s3.amazonaws.com/discourse-1.3.0.box libvirt
    Downloading box 0 from http://discourse-vms.s3.amazonaws.com/discourse-1.3.0.box
    Extracting box file to a temporary directory.
    Converting 0 from virtualbox to libvirt.
       (100.00/100%)
    Cleaning up temporary files.

    $ vagrant box list
    0 (libvirt, 0)

**Comment by sciurus** [comment]
This is a similar issue to #70
